{% comment %}
THIS FILE WAS AUTO-GENERATED BY CODE IN //depot/google3/experimental/users/kenton/protobuf_docs.
DO NOT EDIT THIS FILE DIRECTLY.
{% endcomment %}

{% include "protocol-buffers/_local_variables.html" %}

<html devsite>
  <head>
    <title>{{page_title}}</title>
    <meta name="project_path" value="/protocol-buffers/_project.yaml" />
    <meta name="book_path" value="/protocol-buffers/_book.yaml" />
  </head>
  <body>
